/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Blocks.java
 *
 * Created on 06/08/2011, 03:18:23 PM
 */
package presentation;

/**
 *
 * @author ErickMan
 */
public class Blocks extends javax.swing.JFrame {

    /** Creates new form Blocks */
    public Blocks() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPBlocks = new javax.swing.JPanel();
        JPTitleBlocks = new javax.swing.JPanel();
        JLBBlocks = new javax.swing.JLabel();
        JLBChooseBlocks = new javax.swing.JLabel();
        JBNickname = new javax.swing.JLabel();
        JTFNickname = new javax.swing.JTextField();
        JCBOptionBlocks = new javax.swing.JComboBox();
        JBBlocks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPBlocks.setBackground(new java.awt.Color(204, 204, 204));
        JPBlocks.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));

        JPTitleBlocks.setBackground(new java.awt.Color(204, 204, 204));
        JPTitleBlocks.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));

        JLBBlocks.setFont(new java.awt.Font("Tahoma", 1, 14));
        JLBBlocks.setForeground(new java.awt.Color(153, 0, 0));
        JLBBlocks.setText("Blocks");

        javax.swing.GroupLayout JPTitleBlocksLayout = new javax.swing.GroupLayout(JPTitleBlocks);
        JPTitleBlocks.setLayout(JPTitleBlocksLayout);
        JPTitleBlocksLayout.setHorizontalGroup(
            JPTitleBlocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPTitleBlocksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBBlocks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPTitleBlocksLayout.setVerticalGroup(
            JPTitleBlocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBBlocks)
        );

        JLBChooseBlocks.setFont(new java.awt.Font("Tahoma", 0, 14));
        JLBChooseBlocks.setForeground(new java.awt.Color(153, 0, 0));
        JLBChooseBlocks.setText("Choose an option :");

        JBNickname.setFont(new java.awt.Font("Tahoma", 0, 14));
        JBNickname.setForeground(new java.awt.Color(153, 0, 0));
        JBNickname.setText("Nickname :");

        JTFNickname.setBackground(new java.awt.Color(230, 230, 230));
        JTFNickname.setFont(new java.awt.Font("Tahoma", 2, 11));

        JCBOptionBlocks.setForeground(new java.awt.Color(153, 0, 0));
        JCBOptionBlocks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Add", "Remove" }));

        JBBlocks.setFont(new java.awt.Font("Tahoma", 1, 12));
        JBBlocks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Camisa.png"))); // NOI18N
        JBBlocks.setText("OK");

        javax.swing.GroupLayout JPBlocksLayout = new javax.swing.GroupLayout(JPBlocks);
        JPBlocks.setLayout(JPBlocksLayout);
        JPBlocksLayout.setHorizontalGroup(
            JPBlocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBlocksLayout.createSequentialGroup()
                .addGroup(JPBlocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPBlocksLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(JPBlocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JPBlocksLayout.createSequentialGroup()
                                .addComponent(JBNickname)
                                .addGap(18, 18, 18)
                                .addComponent(JTFNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPBlocksLayout.createSequentialGroup()
                                .addComponent(JLBChooseBlocks)
                                .addGap(18, 18, 18)
                                .addComponent(JCBOptionBlocks, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(JPBlocksLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(JBBlocks, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPBlocksLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(JPTitleBlocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        JPBlocksLayout.setVerticalGroup(
            JPBlocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBlocksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPTitleBlocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(JPBlocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBChooseBlocks)
                    .addComponent(JCBOptionBlocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPBlocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBNickname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(JBBlocks)
                .addContainerGap())
        );

        getContentPane().add(JPBlocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Blocks().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBlocks;
    private javax.swing.JLabel JBNickname;
    private javax.swing.JComboBox JCBOptionBlocks;
    private javax.swing.JLabel JLBBlocks;
    private javax.swing.JLabel JLBChooseBlocks;
    private javax.swing.JPanel JPBlocks;
    private javax.swing.JPanel JPTitleBlocks;
    private javax.swing.JTextField JTFNickname;
    // End of variables declaration//GEN-END:variables
}
