/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChatWindow1.java
 *
 * Created on 22/08/2011, 08:12:42 PM
 */
package presentation;

import controller.ChatWindowController;
import controller.ChatWindowList;
import controller.LogController;
import domain.Utildomain;
import java.awt.Image;
import java.io.File;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author ErickMan
 */
public class BrodcastWindow extends javax.swing.JFrame {
private final JFileChooser JFCBrowse;
public static boolean savechat;
public  static JTextArea lol;
File fileImagen;
    /** Creates new form ChatWindow1 */
    public BrodcastWindow() {
        initComponents();

    JFCBrowse= new JFileChooser();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRBSaveChatNo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAconvertation = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAmyMessage = new javax.swing.JTextArea();
        JLBChatAvatar = new javax.swing.JLabel();
        JBSend = new javax.swing.JButton();
        jBImageToSend = new javax.swing.JButton();
        JLBChat = new javax.swing.JLabel();
        JLBBurgundyChat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Broadcast");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 130, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Save CHAT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        jRadioButton1.setBackground(new java.awt.Color(102, 0, 0));
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("YES");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 50, -1));

        jRBSaveChatNo.setBackground(new java.awt.Color(102, 0, 0));
        jRBSaveChatNo.setForeground(new java.awt.Color(255, 255, 255));
        jRBSaveChatNo.setText("NO");
        jRBSaveChatNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSaveChatNoActionPerformed(evt);
            }
        });
        getContentPane().add(jRBSaveChatNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 50, -1));

        jTAconvertation.setColumns(20);
        jTAconvertation.setRows(5);
        jScrollPane1.setViewportView(jTAconvertation);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 380, 190));

        jTAmyMessage.setColumns(20);
        jTAmyMessage.setRows(5);
        jScrollPane2.setViewportView(jTAmyMessage);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 380, 90));

        JLBChatAvatar.setForeground(new java.awt.Color(255, 255, 255));
        JLBChatAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Av1.png"))); // NOI18N
        getContentPane().add(JLBChatAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 90, 110));

        JBSend.setFont(new java.awt.Font("Tahoma", 1, 12));
        JBSend.setText("Send");
        JBSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSendActionPerformed(evt);
            }
        });
        getContentPane().add(JBSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 120, 50));

        jBImageToSend.setFont(new java.awt.Font("Tahoma", 1, 12));
        jBImageToSend.setText("Send Picture");
        jBImageToSend.setActionCommand("Send\nPicture");
        jBImageToSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImageToSendActionPerformed(evt);
            }
        });
        getContentPane().add(jBImageToSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 120, 30));

        JLBChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/chat.png"))); // NOI18N
        getContentPane().add(JLBChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 418));

        JLBBurgundyChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Bigole.png"))); // NOI18N
        getContentPane().add(JLBBurgundyChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSendActionPerformed
        // TODO add your handling code here:
       if(! ChatWindowController.SendMessageBroadcast(jTAmyMessage, LogController.getNickname(),savechat))
       {
       
          ErrorSendingmessage SIWindow = new ErrorSendingmessage();
          SIWindow.setWindowFather(this, true);
          SIWindow.setVisible(true);
          this.setEnabled(false);
       }
           
    }//GEN-LAST:event_JBSendActionPerformed

    private void jBImageToSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImageToSendActionPerformed
        // TODO add your handling code here:
       // ChatWindowController.SendImage(JFCBrowse, this,jLFriendNickname.getText(),LogController.getNickname());
    }//GEN-LAST:event_jBImageToSendActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
   
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jRBSaveChatNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSaveChatNoActionPerformed
        // TODO add your handling code here:
        savechat = false;
    }//GEN-LAST:event_jRBSaveChatNoActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        savechat = true;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BrodcastWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBSend;
    private javax.swing.JLabel JLBBurgundyChat;
    private javax.swing.JLabel JLBChat;
    private javax.swing.JLabel JLBChatAvatar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBImageToSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRBSaveChatNo;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTextArea jTAconvertation;
    private javax.swing.JTextArea jTAmyMessage;
    // End of variables declaration//GEN-END:variables

    public JFrame windowFather;

    public static JTextArea getjTAconvertation() {
        return jTAconvertation;
    }

    public static void setjTAconvertation(JTextArea jTAconvertation) {
        BrodcastWindow.jTAconvertation = jTAconvertation;
    }

    public JFrame getWindowFather() {
        return windowFather;
    }

    public void setWindowFather(JFrame windowFather) {
        this.windowFather = windowFather;
    }
    
}
