/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChooseAvatar.java
 *
 * Created on 16/08/2011, 09:15:39 PM
 */
package presentation;

import controller.AvatarController;
import java.io.File;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author ErickMan
 */
public class ChooseAvatar extends javax.swing.JFrame {

    /** Creates new form ChooseAvatar */
    private final JFileChooser JFCBrowse;
    File fileImagen;
  
    public ChooseAvatar(JLabel JLBavatar) {
        initComponents();
         this.setLocationRelativeTo(null);
        JFCBrowse = new JFileChooser();
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBBrowse = new javax.swing.JButton();
        JLBAvatr1 = new javax.swing.JLabel();
        JLBAvatr = new javax.swing.JLabel();
        JPChooseAvatar = new javax.swing.JPanel();
        JLBChooseAvatar = new javax.swing.JLabel();
        JBAvatarM2 = new javax.swing.JButton();
        JSChooseA2 = new javax.swing.JSeparator();
        JLBFemale = new javax.swing.JLabel();
        JBAvatarM3 = new javax.swing.JButton();
        JBAvatarF2 = new javax.swing.JButton();
        JLBMale = new javax.swing.JLabel();
        JBAvatarM1 = new javax.swing.JButton();
        JBAvatarF3 = new javax.swing.JButton();
        JBAvatarF1 = new javax.swing.JButton();
        JSChooseA1 = new javax.swing.JSeparator();
        JLBBurgundyAvatar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBBrowse.setFont(new java.awt.Font("Tahoma", 1, 14));
        JBBrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Camisa.png"))); // NOI18N
        JBBrowse.setText("Browse");
        JBBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(JBBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 140, 40));

        JLBAvatr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/lll.png"))); // NOI18N
        getContentPane().add(JLBAvatr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        JLBAvatr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/lll.png"))); // NOI18N
        getContentPane().add(JLBAvatr, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        JPChooseAvatar.setBackground(new java.awt.Color(153, 0, 0));
        JPChooseAvatar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        JLBChooseAvatar.setFont(new java.awt.Font("Tahoma", 1, 24));
        JLBChooseAvatar.setForeground(new java.awt.Color(204, 204, 204));
        JLBChooseAvatar.setText("Choose Avatar");

        javax.swing.GroupLayout JPChooseAvatarLayout = new javax.swing.GroupLayout(JPChooseAvatar);
        JPChooseAvatar.setLayout(JPChooseAvatarLayout);
        JPChooseAvatarLayout.setHorizontalGroup(
            JPChooseAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPChooseAvatarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLBChooseAvatar)
                .addContainerGap())
        );
        JPChooseAvatarLayout.setVerticalGroup(
            JPChooseAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPChooseAvatarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBChooseAvatar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(JPChooseAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, 50));

        JBAvatarM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Av2.png"))); // NOI18N
        JBAvatarM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAvatarM2ActionPerformed(evt);
            }
        });
        getContentPane().add(JBAvatarM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 100, 100));
        getContentPane().add(JSChooseA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 490, 10));

        JLBFemale.setFont(new java.awt.Font("Tahoma", 1, 18));
        JLBFemale.setForeground(new java.awt.Color(204, 204, 204));
        JLBFemale.setText("Female :");
        getContentPane().add(JLBFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        JBAvatarM3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Avv3.png"))); // NOI18N
        JBAvatarM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAvatarM3ActionPerformed(evt);
            }
        });
        getContentPane().add(JBAvatarM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 100, 100));

        JBAvatarF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Av5.png"))); // NOI18N
        JBAvatarF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAvatarF2ActionPerformed(evt);
            }
        });
        getContentPane().add(JBAvatarF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 100, 100));

        JLBMale.setFont(new java.awt.Font("Tahoma", 1, 18));
        JLBMale.setForeground(new java.awt.Color(204, 204, 204));
        JLBMale.setText("Male :");
        getContentPane().add(JLBMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        JBAvatarM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Av1.png"))); // NOI18N
        JBAvatarM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAvatarM1ActionPerformed(evt);
            }
        });
        getContentPane().add(JBAvatarM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 100, 100));

        JBAvatarF3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Avv6.png"))); // NOI18N
        JBAvatarF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAvatarF3ActionPerformed(evt);
            }
        });
        getContentPane().add(JBAvatarF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 100, 100));

        JBAvatarF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Av4.png"))); // NOI18N
        JBAvatarF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAvatarF1ActionPerformed(evt);
            }
        });
        getContentPane().add(JBAvatarF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 100, 100));
        getContentPane().add(JSChooseA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 490, 10));

        JLBBurgundyAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Bigole.png"))); // NOI18N
        getContentPane().add(JLBBurgundyAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 531, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBrowseActionPerformed
        
  AvatarController.browsed(JFCBrowse, this);
        // TODO add your handling code here:
    }//GEN-LAST:event_JBBrowseActionPerformed

    private void JBAvatarM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAvatarM1ActionPerformed
        // TODO add your handling code here:
         try {
            AvatarController.changeavatar("src/Av1.PNG", this);
        } catch (ParseException ex) {
            Logger.getLogger(ChooseAvatar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBAvatarM1ActionPerformed

    private void JBAvatarM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAvatarM2ActionPerformed
           try {
            AvatarController.changeavatar("src/Av2.PNG", this);
        } catch (ParseException ex) {
            Logger.getLogger(ChooseAvatar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBAvatarM2ActionPerformed

    private void JBAvatarM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAvatarM3ActionPerformed
        // TODO add your handling code here:
             try {
            AvatarController.changeavatar("src/Avv3.PNG", this);
        } catch (ParseException ex) {
            Logger.getLogger(ChooseAvatar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBAvatarM3ActionPerformed

    private void JBAvatarF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAvatarF1ActionPerformed
        // TODO add your handling code here:
           try {
            AvatarController.changeavatar("src/Av4.PNG", this);
        } catch (ParseException ex) {
            Logger.getLogger(ChooseAvatar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBAvatarF1ActionPerformed

    private void JBAvatarF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAvatarF2ActionPerformed
        // TODO add your handling code here:
          try {
            AvatarController.changeavatar("src/Av5.PNG", this);
        } catch (ParseException ex) {
            Logger.getLogger(ChooseAvatar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBAvatarF2ActionPerformed

    private void JBAvatarF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAvatarF3ActionPerformed
        // TODO add your handling code here
          try {
            AvatarController.changeavatar("src/Avv6.PNG", this);
        } catch (ParseException ex) {
            Logger.getLogger(ChooseAvatar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBAvatarF3ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
         this.getWindowFather().setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.getWindowFather().setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                //new ChooseAvatar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAvatarF1;
    private javax.swing.JButton JBAvatarF2;
    private javax.swing.JButton JBAvatarF3;
    private javax.swing.JButton JBAvatarM1;
    private javax.swing.JButton JBAvatarM2;
    private javax.swing.JButton JBAvatarM3;
    private javax.swing.JButton JBBrowse;
    private javax.swing.JLabel JLBAvatr;
    private javax.swing.JLabel JLBAvatr1;
    private javax.swing.JLabel JLBBurgundyAvatar;
    private javax.swing.JLabel JLBChooseAvatar;
    private javax.swing.JLabel JLBFemale;
    private javax.swing.JLabel JLBMale;
    private javax.swing.JPanel JPChooseAvatar;
    private javax.swing.JSeparator JSChooseA1;
    private javax.swing.JSeparator JSChooseA2;
    // End of variables declaration//GEN-END:variables
 public JLabel avatar;
 public JFrame windowFather;
    public JLabel getAvatar() {
        return avatar;
    }

    public void setAvatar(JLabel avatar) {
        this.avatar = avatar;
    }
    
    public JFrame getWindowFather() {
        return windowFather;
    }

    public void setWindowFather(JFrame windowFather) {
        this.windowFather = windowFather;
    }
    
  
}
