/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ErrorSignIn.java
 *
 * Created on 15/08/2011, 09:29:28 PM
 */
package presentation;

import javax.swing.JFrame;

/**
 *
 * @author ErickMan
 */
public class ErrorSendingmessage extends javax.swing.JFrame {

    /** Creates new form ErrorSignIn */
    public ErrorSendingmessage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
       
  public void setWindowFather(JFrame windowFather)
    {
        this.windowFather = windowFather;
    }
    
    
       public void setWindowFather(JFrame windowFather, boolean blockWindowFather)
    {
        this.windowFather = windowFather;
        
        if (blockWindowFather)
            this.windowFather.setEnabled(false);
        
        this.setAlwaysOnTop(true);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPErrorSignin = new javax.swing.JPanel();
        JBErrorSignin = new javax.swing.JButton();
        JLBErrorSignin = new javax.swing.JLabel();
        JLBErrorLogin1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JPErrorSignin.setBackground(new java.awt.Color(204, 204, 204));
        JPErrorSignin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));

        JBErrorSignin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JBErrorSignin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Camisa.png"))); // NOI18N
        JBErrorSignin.setText("OK");
        JBErrorSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBErrorSigninActionPerformed(evt);
            }
        });

        JLBErrorSignin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/error.png"))); // NOI18N

        JLBErrorLogin1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLBErrorLogin1.setForeground(new java.awt.Color(153, 0, 0));
        JLBErrorLogin1.setText("The message can be sended beacause your friend is offline");

        javax.swing.GroupLayout JPErrorSigninLayout = new javax.swing.GroupLayout(JPErrorSignin);
        JPErrorSignin.setLayout(JPErrorSigninLayout);
        JPErrorSigninLayout.setHorizontalGroup(
            JPErrorSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPErrorSigninLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBErrorSignin)
                .addGap(18, 18, 18)
                .addComponent(JLBErrorLogin1)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPErrorSigninLayout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(JBErrorSignin)
                .addGap(190, 190, 190))
        );
        JPErrorSigninLayout.setVerticalGroup(
            JPErrorSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPErrorSigninLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPErrorSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPErrorSigninLayout.createSequentialGroup()
                        .addComponent(JLBErrorSignin)
                        .addGap(39, 39, 39))
                    .addGroup(JPErrorSigninLayout.createSequentialGroup()
                        .addComponent(JLBErrorLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(JBErrorSignin)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPErrorSignin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPErrorSignin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBErrorSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBErrorSigninActionPerformed
        // TODO add your handling code here:
        this.windowFather.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_JBErrorSigninActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ErrorSendingmessage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBErrorSignin;
    private javax.swing.JLabel JLBErrorLogin1;
    private javax.swing.JLabel JLBErrorSignin;
    private javax.swing.JPanel JPErrorSignin;
    // End of variables declaration//GEN-END:variables
private JFrame windowFather;

    
}
