/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ErrorSignIn.java
 *
 * Created on 15/08/2011, 09:29:28 PM
 */
package presentation;

import javax.swing.JFrame;

/**
 *
 * @author ErickMan
 */
public class ErrorSignIn extends javax.swing.JFrame {

    /** Creates new form ErrorSignIn */
    public ErrorSignIn() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
       

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPErrorSignin = new javax.swing.JPanel();
        JLBErrorNickPass = new javax.swing.JLabel();
        JBErrorSignin = new javax.swing.JButton();
        JLBErrorSignin = new javax.swing.JLabel();
        JLBErrorLogin1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JPErrorSignin.setBackground(new java.awt.Color(204, 204, 204));
        JPErrorSignin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));

        JLBErrorNickPass.setFont(new java.awt.Font("Tahoma", 0, 14));
        JLBErrorNickPass.setForeground(new java.awt.Color(153, 0, 0));
        JLBErrorNickPass.setText("The nickname or password is incorrect");

        JBErrorSignin.setFont(new java.awt.Font("Tahoma", 1, 12));
        JBErrorSignin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Camisa.png"))); // NOI18N
        JBErrorSignin.setText("OK");
        JBErrorSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBErrorSigninActionPerformed(evt);
            }
        });

        JLBErrorSignin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/error.png"))); // NOI18N

        JLBErrorLogin1.setFont(new java.awt.Font("Tahoma", 1, 18));
        JLBErrorLogin1.setForeground(new java.awt.Color(153, 0, 0));
        JLBErrorLogin1.setText("You can't sign in JChat");

        javax.swing.GroupLayout JPErrorSigninLayout = new javax.swing.GroupLayout(JPErrorSignin);
        JPErrorSignin.setLayout(JPErrorSigninLayout);
        JPErrorSigninLayout.setHorizontalGroup(
            JPErrorSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPErrorSigninLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBErrorSignin)
                .addGroup(JPErrorSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPErrorSigninLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(JLBErrorLogin1))
                    .addGroup(JPErrorSigninLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(JBErrorSignin))
                    .addGroup(JPErrorSigninLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JLBErrorNickPass)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        JPErrorSigninLayout.setVerticalGroup(
            JPErrorSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPErrorSigninLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPErrorSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLBErrorSignin)
                    .addGroup(JPErrorSigninLayout.createSequentialGroup()
                        .addComponent(JLBErrorLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLBErrorNickPass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBErrorSignin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPErrorSignin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPErrorSignin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBErrorSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBErrorSigninActionPerformed
        // TODO add your handling code here:
         this.getWindowFather().setEnabled(true);        
        this.dispose();    
    }//GEN-LAST:event_JBErrorSigninActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ErrorSignIn().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBErrorSignin;
    private javax.swing.JLabel JLBErrorLogin1;
    private javax.swing.JLabel JLBErrorNickPass;
    private javax.swing.JLabel JLBErrorSignin;
    private javax.swing.JPanel JPErrorSignin;
    // End of variables declaration//GEN-END:variables
private JFrame windowFather;
    public JFrame getWindowFather() {
        return windowFather;
    }

    public void setWindowFather(JFrame windowFather) {
        this.windowFather = windowFather;
    }
    
}
