/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ErrorNickname.java
 *
 * Created on 10/08/2011, 08:49:46 PM
 */
package presentation;

import javax.swing.JFrame;

/**
 *
 * @author ErickMan
 */
public class ErrorNickname2 extends javax.swing.JFrame {

    /** Creates new form ErrorNickname */
    public ErrorNickname2() {
        initComponents();
    }
             public void setWindowFather(JFrame windowFather)
    {
        this.windowFather = windowFather;
    }
    
    
       public void setWindowFather(JFrame windowFather, boolean blockWindowFather)
    {
        this.windowFather = windowFather;
        
        if (blockWindowFather)
            this.windowFather.setEnabled(false);
        
        this.setAlwaysOnTop(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPErrorNickname = new javax.swing.JPanel();
        JLBErrorNickname = new javax.swing.JLabel();
        JBErrorNickname = new javax.swing.JButton();
        JLBErrorNick = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JPErrorNickname.setBackground(new java.awt.Color(204, 204, 204));
        JPErrorNickname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));

        JLBErrorNickname.setFont(new java.awt.Font("Tahoma", 0, 14));
        JLBErrorNickname.setForeground(new java.awt.Color(153, 0, 0));
        JLBErrorNickname.setText("The nickname you enter is wrong. Please enter again to add a friend ");

        JBErrorNickname.setFont(new java.awt.Font("Tahoma", 1, 12));
        JBErrorNickname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Camisa.png"))); // NOI18N
        JBErrorNickname.setText("OK");
        JBErrorNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBErrorNicknameActionPerformed(evt);
            }
        });

        JLBErrorNick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/error.png"))); // NOI18N

        javax.swing.GroupLayout JPErrorNicknameLayout = new javax.swing.GroupLayout(JPErrorNickname);
        JPErrorNickname.setLayout(JPErrorNicknameLayout);
        JPErrorNicknameLayout.setHorizontalGroup(
            JPErrorNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPErrorNicknameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPErrorNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JBErrorNickname)
                    .addGroup(JPErrorNicknameLayout.createSequentialGroup()
                        .addComponent(JLBErrorNick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JLBErrorNickname)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPErrorNicknameLayout.setVerticalGroup(
            JPErrorNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPErrorNicknameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPErrorNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLBErrorNick)
                    .addComponent(JLBErrorNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JBErrorNickname)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPErrorNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPErrorNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBErrorNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBErrorNicknameActionPerformed
        // TODO add your handling code here:
          this.windowFather.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_JBErrorNicknameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ErrorNickname2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBErrorNickname;
    private javax.swing.JLabel JLBErrorNick;
    private javax.swing.JLabel JLBErrorNickname;
    private javax.swing.JPanel JPErrorNickname;
    // End of variables declaration//GEN-END:variables
private JFrame windowFather;
}
