/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IncompleteField.java
 *
 * Created on 11/08/2011, 08:16:15 PM
 */
package presentation;

import javax.swing.JFrame;

/**
 *
 * @author Jesus Parada & Erick Medina
 */
public class IncompleteField extends javax.swing.JFrame {

    /** Creates new form IncompleteField */
    public IncompleteField() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPIncomplete = new javax.swing.JPanel();
        JLBIncomplete = new javax.swing.JLabel();
        JBIncomplete = new javax.swing.JButton();
        JLBErrorIncomplete = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPIncomplete.setBackground(new java.awt.Color(204, 204, 204));
        JPIncomplete.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));

        JLBIncomplete.setFont(new java.awt.Font("Tahoma", 0, 14));
        JLBIncomplete.setForeground(new java.awt.Color(153, 0, 0));
        JLBIncomplete.setText("There is information that was not completed in one or more fields");

        JBIncomplete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JBIncomplete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Camisa.png"))); // NOI18N
        JBIncomplete.setText("OK");
        JBIncomplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBIncompleteActionPerformed(evt);
            }
        });

        JLBErrorIncomplete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/error.png"))); // NOI18N

        javax.swing.GroupLayout JPIncompleteLayout = new javax.swing.GroupLayout(JPIncomplete);
        JPIncomplete.setLayout(JPIncompleteLayout);
        JPIncompleteLayout.setHorizontalGroup(
            JPIncompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPIncompleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBErrorIncomplete)
                .addGap(18, 18, 18)
                .addComponent(JLBIncomplete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPIncompleteLayout.createSequentialGroup()
                .addContainerGap(351, Short.MAX_VALUE)
                .addComponent(JBIncomplete)
                .addGap(19, 19, 19))
        );
        JPIncompleteLayout.setVerticalGroup(
            JPIncompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPIncompleteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPIncompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLBErrorIncomplete)
                    .addComponent(JLBIncomplete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBIncomplete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPIncomplete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPIncomplete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBIncompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBIncompleteActionPerformed
      this.getWindowFather().setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_JBIncompleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new IncompleteField().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBIncomplete;
    private javax.swing.JLabel JLBErrorIncomplete;
    private javax.swing.JLabel JLBIncomplete;
    private javax.swing.JPanel JPIncomplete;
    // End of variables declaration//GEN-END:variables
private JFrame windowFather;
 public JFrame getWindowFather() {
        return windowFather;
    }

    public void setWindowFather(JFrame windowFather) {
        this.windowFather = windowFather;
    }
}
