/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JChat2.java
 *
 * Created on 15/08/2011, 10:18:11 PM
 */
package presentation;

import controller.AvatarController;
import controller.ChatWindowController;
import controller.ChatWindowList;
import controller.JChatController;
import controller.LogController;
import domain.Utildomain;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Enumeration;
import java.util.List;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTree;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;

/**
 *
 * @author ErickMan
 */
public class JChat extends javax.swing.JFrame {

    /** Creates new form JChat2 */
    public  JTree tree;
    public  JTree tree2;
    public static String friendnicknameChat="";
    public static ChatWindowList chat =null ;
    
    public JChat() throws ParseException {
        initComponents();

     JChatController.JChatConstructor(this, this.JLBImageNickname, this.JBContacts, this.JBBlocks,  this.jLMyNickname,  JChatController.isStatus());
    tree2= JChatController.loadtree(this.tree, this.JPpanel);
    if (tree2 !=null)
    { 
    tree2.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent me) {
                doMouseClicked(me);
                }
            });
    }
    }
     void doMouseClicked(MouseEvent me)
     {
    TreePath tp = tree2.getPathForLocation(me.getX(), me.getY());
    String SeparatorNode = ",";
    String SEPARADOR = "]";
    if (tp != null)
    {
       String[] friendnick = tp.toString().split(SeparatorNode);
            String  friend =friendnick[3].replace("]","");
  
  friendnicknameChat=friend.trim();

       boolean chato =ChatWindowController.searchWindow(friendnicknameChat);
       if (chato == true)
        System.out.println("There is a window whit this name ");   
       else
       {
           ChatWindow1 chats = new ChatWindow1();
           chats.setVisible(true);
           
       }

    }
    }
    
  

    public static String getFriendnicknameChat() {
        return friendnicknameChat;
    }

    public static void setFriendnicknameChat(String friendnicknameChat) {
        JChat.friendnicknameChat = friendnicknameChat;
    }


 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLBDown = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JLBImageNickname = new javax.swing.JLabel();
        jBBroadcast = new javax.swing.JButton();
        jLMyNickname = new javax.swing.JLabel();
        JBContacts = new javax.swing.JButton();
        JLBCommentContacts = new javax.swing.JLabel();
        JBBlocks = new javax.swing.JButton();
        JLBCommentBlocks = new javax.swing.JLabel();
        JSMainWindow = new javax.swing.JSeparator();
        LBDelete = new javax.swing.JButton();
        JLBUp = new javax.swing.JLabel();
        JPpanel = new javax.swing.JPanel();
        JLBSoccerField = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMLogout = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        JMILogout = new javax.swing.JMenuItem();
        JMPreferences = new javax.swing.JMenu();
        JMIPort = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        JMIIP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Down.png"))); // NOI18N
        getContentPane().add(JLBDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, -1, 60));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setText("Change Avatar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));
        getContentPane().add(JLBImageNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, 130));

        jBBroadcast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/pelota.png"))); // NOI18N
        jBBroadcast.setText("BroadCast");
        jBBroadcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBroadcastActionPerformed(evt);
            }
        });
        getContentPane().add(jBBroadcast, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 570, 110, -1));

        jLMyNickname.setBackground(new java.awt.Color(153, 0, 0));
        jLMyNickname.setFont(new java.awt.Font("Comic Sans MS", 0, 18));
        jLMyNickname.setForeground(new java.awt.Color(102, 0, 0));
        jLMyNickname.setText("jLabel1");
        getContentPane().add(jLMyNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 100, 30));

        JBContacts.setFont(new java.awt.Font("Tahoma", 1, 12));
        JBContacts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Jerse.png"))); // NOI18N
        JBContacts.setText("Contacts");
        JBContacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBContactsActionPerformed(evt);
            }
        });
        getContentPane().add(JBContacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        JLBCommentContacts.setFont(new java.awt.Font("Tahoma", 2, 12));
        JLBCommentContacts.setForeground(new java.awt.Color(153, 0, 0));
        JLBCommentContacts.setText("add or remove contacts");
        getContentPane().add(JLBCommentContacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 140, -1));

        JBBlocks.setFont(new java.awt.Font("Tahoma", 1, 12));
        JBBlocks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Jerse.png"))); // NOI18N
        JBBlocks.setText("Blocks");
        getContentPane().add(JBBlocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 130, -1));

        JLBCommentBlocks.setFont(new java.awt.Font("Tahoma", 2, 12));
        JLBCommentBlocks.setForeground(new java.awt.Color(153, 0, 0));
        JLBCommentBlocks.setText("add or remove blocks");
        getContentPane().add(JLBCommentBlocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 120, -1));
        getContentPane().add(JSMainWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 570, 10));

        LBDelete.setFont(new java.awt.Font("Tahoma", 1, 10));
        LBDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/X.png"))); // NOI18N
        LBDelete.setText("Delete Account");
        getContentPane().add(LBDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        JLBUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Up.png"))); // NOI18N
        getContentPane().add(JLBUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));
        getContentPane().add(JPpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 540, 260));

        JLBSoccerField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Gramasoccer.png"))); // NOI18N
        getContentPane().add(JLBSoccerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 670));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 12));

        JMLogout.setText("Main");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/pelota.png"))); // NOI18N
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JMLogout.add(jMenuItem1);

        JMILogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        JMILogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/X.png"))); // NOI18N
        JMILogout.setText("Exit");
        JMILogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMILogoutActionPerformed(evt);
            }
        });
        JMLogout.add(JMILogout);

        jMenuBar1.add(JMLogout);

        JMPreferences.setText("Preferences");

        JMIPort.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        JMIPort.setText("Port");
        JMPreferences.add(JMIPort);
        JMPreferences.add(jSeparator2);

        JMIIP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        JMIIP.setText("IP");
        JMPreferences.add(JMIIP);

        jMenuBar1.add(JMPreferences);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JChatController.changeAvatar(this,JLBImageNickname );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JBContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBContactsActionPerformed
       JChatController.ContactsControl(this);
       
    }//GEN-LAST:event_JBContactsActionPerformed

    private void JMILogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMILogoutActionPerformed
        // TODO add your handling code here:
         JChatController.logOutcontrol(this);
    
     
    }//GEN-LAST:event_JMILogoutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
          About SiWindow= new About();
          
         SiWindow.setWindowFather(this, true);
         SiWindow.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jBBroadcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBroadcastActionPerformed
        // TODO add your handling code here:
        BrodcastWindow win = new BrodcastWindow();
            win.setVisible(true);            
    }//GEN-LAST:event_jBBroadcastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new JChat().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(JChat.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBlocks;
    private javax.swing.JButton JBContacts;
    private javax.swing.JLabel JLBCommentBlocks;
    private javax.swing.JLabel JLBCommentContacts;
    private javax.swing.JLabel JLBDown;
    private javax.swing.JLabel JLBImageNickname;
    private javax.swing.JLabel JLBSoccerField;
    private javax.swing.JLabel JLBUp;
    private javax.swing.JMenuItem JMIIP;
    private javax.swing.JMenuItem JMILogout;
    private javax.swing.JMenuItem JMIPort;
    private javax.swing.JMenu JMLogout;
    private javax.swing.JMenu JMPreferences;
    private javax.swing.JPanel JPpanel;
    private javax.swing.JSeparator JSMainWindow;
    private javax.swing.JButton LBDelete;
    private javax.swing.JButton jBBroadcast;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLMyNickname;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
private JFrame windowFather;
    public JFrame getWindowFather() {
        return windowFather;
    }

    public void setWindowFather(JFrame windowFather) {
        this.windowFather = windowFather;
    }

    public static ChatWindowList getChat() {
        return chat;
    }

    public static void setChat(ChatWindowList chat) {
        JChat.chat = chat;
    }

    public  JLabel getJLBImageNickname() {
        return JLBImageNickname;
    }

    public void setJLBImageNickname(JLabel JLBImageNickname) {
        this.JLBImageNickname = JLBImageNickname;
    }
    
    
}
