/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MoveContact.java
 *
 * Created on 10/08/2011, 09:24:52 PM
 */
package presentation;

/**
 *
 * @author ErickMan
 */
public class MoveContact extends javax.swing.JFrame {

    /** Creates new form MoveContact */
    public MoveContact() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPBlocks = new javax.swing.JPanel();
        JPMoveContact = new javax.swing.JPanel();
        JLBMoveContact = new javax.swing.JLabel();
        JLBContactMove = new javax.swing.JLabel();
        JTFMoveContact = new javax.swing.JTextField();
        JBMoveContact = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPBlocks.setBackground(new java.awt.Color(204, 204, 204));
        JPBlocks.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));

        JPMoveContact.setBackground(new java.awt.Color(204, 204, 204));
        JPMoveContact.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));

        JLBMoveContact.setFont(new java.awt.Font("Tahoma", 1, 14));
        JLBMoveContact.setForeground(new java.awt.Color(153, 0, 0));
        JLBMoveContact.setText("Contact Move");

        javax.swing.GroupLayout JPMoveContactLayout = new javax.swing.GroupLayout(JPMoveContact);
        JPMoveContact.setLayout(JPMoveContactLayout);
        JPMoveContactLayout.setHorizontalGroup(
            JPMoveContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPMoveContactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBMoveContact)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPMoveContactLayout.setVerticalGroup(
            JPMoveContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBMoveContact)
        );

        JLBContactMove.setFont(new java.awt.Font("Tahoma", 0, 14));
        JLBContactMove.setForeground(new java.awt.Color(153, 0, 0));
        JLBContactMove.setText("Destination Block :");

        JTFMoveContact.setBackground(new java.awt.Color(230, 230, 230));
        JTFMoveContact.setFont(new java.awt.Font("Tahoma", 2, 11));

        JBMoveContact.setFont(new java.awt.Font("Tahoma", 1, 12));
        JBMoveContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Camisa.png"))); // NOI18N
        JBMoveContact.setText("OK");

        javax.swing.GroupLayout JPBlocksLayout = new javax.swing.GroupLayout(JPBlocks);
        JPBlocks.setLayout(JPBlocksLayout);
        JPBlocksLayout.setHorizontalGroup(
            JPBlocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBlocksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBContactMove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTFMoveContact, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBlocksLayout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(JBMoveContact, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(JPBlocksLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(JPMoveContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        JPBlocksLayout.setVerticalGroup(
            JPBlocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBlocksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPMoveContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(JPBlocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBContactMove)
                    .addComponent(JTFMoveContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JBMoveContact)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPBlocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPBlocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MoveContact().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBMoveContact;
    private javax.swing.JLabel JLBContactMove;
    private javax.swing.JLabel JLBMoveContact;
    private javax.swing.JPanel JPBlocks;
    private javax.swing.JPanel JPMoveContact;
    private javax.swing.JTextField JTFMoveContact;
    // End of variables declaration//GEN-END:variables
}
