/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ThanksForRegister.java
 *
 * Created on 10/08/2011, 09:09:24 PM
 */
package presentation;

import javax.swing.JFrame;

/**
 *
 * @author ErickMan
 */
public class ThanksForRegister extends javax.swing.JFrame {

    /** Creates new form ThanksForRegister */
    public ThanksForRegister() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
      
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPSucessRegister = new javax.swing.JPanel();
        JLBErrorNickname = new javax.swing.JLabel();
        JBGotoMainWindow = new javax.swing.JButton();
        JLBShot = new javax.swing.JLabel();
        JLBErrorNickname1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPSucessRegister.setBackground(new java.awt.Color(204, 204, 204));
        JPSucessRegister.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));

        JLBErrorNickname.setFont(new java.awt.Font("Tahoma", 0, 13));
        JLBErrorNickname.setForeground(new java.awt.Color(153, 0, 0));
        JLBErrorNickname.setText("Welcome...Thank you for choosing our application!");

        JBGotoMainWindow.setFont(new java.awt.Font("Tahoma", 1, 12));
        JBGotoMainWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Camisa.png"))); // NOI18N
        JBGotoMainWindow.setText("OK");
        JBGotoMainWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGotoMainWindowActionPerformed(evt);
            }
        });

        JLBShot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Shot.png"))); // NOI18N

        JLBErrorNickname1.setFont(new java.awt.Font("Tahoma", 1, 14));
        JLBErrorNickname1.setForeground(new java.awt.Color(153, 0, 0));
        JLBErrorNickname1.setText("Successful Registration ! ! !");

        javax.swing.GroupLayout JPSucessRegisterLayout = new javax.swing.GroupLayout(JPSucessRegister);
        JPSucessRegister.setLayout(JPSucessRegisterLayout);
        JPSucessRegisterLayout.setHorizontalGroup(
            JPSucessRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSucessRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBShot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPSucessRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPSucessRegisterLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(JLBErrorNickname))
                    .addGroup(JPSucessRegisterLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(JLBErrorNickname1)))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPSucessRegisterLayout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(JBGotoMainWindow)
                .addContainerGap())
        );
        JPSucessRegisterLayout.setVerticalGroup(
            JPSucessRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSucessRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPSucessRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLBShot)
                    .addGroup(JPSucessRegisterLayout.createSequentialGroup()
                        .addComponent(JLBErrorNickname1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLBErrorNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(JBGotoMainWindow)
                .addContainerGap())
        );

        getContentPane().add(JPSucessRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBGotoMainWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGotoMainWindowActionPerformed
        // TODO add your handling code here:
         MainWindow log = new MainWindow();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBGotoMainWindowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ThanksForRegister().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBGotoMainWindow;
    private javax.swing.JLabel JLBErrorNickname;
    private javax.swing.JLabel JLBErrorNickname1;
    private javax.swing.JLabel JLBShot;
    private javax.swing.JPanel JPSucessRegister;
    // End of variables declaration//GEN-END:variables
private JFrame windowFather;
}
