/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserRegistrationWindow.java
 *
 * Created on 16/08/2011, 07:37:10 PM
 */
package presentation;
import controller.RegistrationController;
import controller.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import presentation.ThanksForRegister;


/**
 *
 * @author ErickMan
 */
public class UserRegistrationWindow extends javax.swing.JFrame {

    /** Creates new form UserRegistrationWindow */
    public UserRegistrationWindow() {
        initComponents();
        this.setVisible(true);
        this.JDCBirthDate.getDateEditor().setEnabled(false);
        this.setLocationRelativeTo(null);
    }
    public void setWindowFather(JFrame windowFather)
    {
        this.windowFather = windowFather;
    }
    
    
       public void setWindowFather(JFrame windowFather, boolean blockWindowFather)
    {
        this.windowFather = windowFather;
        
        if (blockWindowFather)
            this.windowFather.setEnabled(false);
        
        this.setAlwaysOnTop(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        JLBRegisterUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JLBName = new javax.swing.JLabel();
        JTFName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        JTFNickname = new javax.swing.JTextField();
        JLBNickname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JLBPassword = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JPFPassword = new javax.swing.JPasswordField();
        JLBLastName = new javax.swing.JLabel();
        JTFLastName = new javax.swing.JTextField();
        JSRegister3 = new javax.swing.JSeparator();
        JLBSecondLastName = new javax.swing.JLabel();
        JTFSecondLastName = new javax.swing.JTextField();
        JSRegister1 = new javax.swing.JSeparator();
        JLBEmail = new javax.swing.JLabel();
        JTFEmail = new javax.swing.JTextField();
        JLBBirthDate = new javax.swing.JLabel();
        JDCBirthDate = new com.toedter.calendar.JDateChooser();
        JSRegister2 = new javax.swing.JSeparator();
        jBCancel = new javax.swing.JButton();
        JBSignUp = new javax.swing.JButton();
        JLBBeTheFirst = new javax.swing.JLabel();
        JLBBurgundyRegister = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBRegisterUser.setFont(new java.awt.Font("Tahoma", 1, 21));
        JLBRegisterUser.setForeground(new java.awt.Color(204, 204, 204));
        JLBRegisterUser.setText("Registration  of  Users  JChat");
        getContentPane().add(JLBRegisterUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Jerseyy.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        JLBName.setFont(new java.awt.Font("Tahoma", 1, 14));
        JLBName.setForeground(new java.awt.Color(204, 204, 204));
        JLBName.setText("Name : ");
        getContentPane().add(JLBName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        JTFName.setBackground(new java.awt.Color(230, 230, 230));
        JTFName.setFont(new java.awt.Font("Tahoma", 2, 11));
        getContentPane().add(JTFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 110, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));

        JTFNickname.setFont(new java.awt.Font("Tahoma", 2, 11));

        JLBNickname.setFont(new java.awt.Font("Tahoma", 1, 14));
        JLBNickname.setForeground(new java.awt.Color(153, 0, 0));
        JLBNickname.setText("Nickname : ");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/pelota.png"))); // NOI18N

        JLBPassword.setFont(new java.awt.Font("Tahoma", 1, 14));
        JLBPassword.setForeground(new java.awt.Color(153, 0, 0));
        JLBPassword.setText("Password : ");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/pelota.png"))); // NOI18N

        JPFPassword.setBackground(new java.awt.Color(230, 230, 230));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLBNickname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLBPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLBNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBPassword)
                            .addComponent(JPFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 580, -1));

        JLBLastName.setFont(new java.awt.Font("Tahoma", 1, 14));
        JLBLastName.setForeground(new java.awt.Color(204, 204, 204));
        JLBLastName.setText("Last Name : ");
        getContentPane().add(JLBLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        JTFLastName.setBackground(new java.awt.Color(230, 230, 230));
        JTFLastName.setFont(new java.awt.Font("Tahoma", 2, 11));
        getContentPane().add(JTFLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 110, -1));
        getContentPane().add(JSRegister3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 690, 10));

        JLBSecondLastName.setFont(new java.awt.Font("Tahoma", 1, 14));
        JLBSecondLastName.setForeground(new java.awt.Color(204, 204, 204));
        JLBSecondLastName.setText("Second Last Name :");
        getContentPane().add(JLBSecondLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        JTFSecondLastName.setBackground(new java.awt.Color(230, 230, 230));
        JTFSecondLastName.setFont(new java.awt.Font("Tahoma", 2, 11));
        getContentPane().add(JTFSecondLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 110, -1));
        getContentPane().add(JSRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 690, 10));

        JLBEmail.setFont(new java.awt.Font("Tahoma", 1, 14));
        JLBEmail.setForeground(new java.awt.Color(204, 204, 204));
        JLBEmail.setText("Email :");
        getContentPane().add(JLBEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        JTFEmail.setBackground(new java.awt.Color(230, 230, 230));
        JTFEmail.setFont(new java.awt.Font("Tahoma", 2, 11));
        getContentPane().add(JTFEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 150, -1));

        JLBBirthDate.setFont(new java.awt.Font("Tahoma", 1, 14));
        JLBBirthDate.setForeground(new java.awt.Color(204, 204, 204));
        JLBBirthDate.setText("Birth Date :");
        getContentPane().add(JLBBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        JDCBirthDate.setBackground(new java.awt.Color(230, 230, 230));
        JDCBirthDate.setDateFormatString("dd/MM/yy");
        getContentPane().add(JDCBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 110, -1));
        getContentPane().add(JSRegister2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 690, 10));

        jBCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Camisa.png"))); // NOI18N
        jBCancel.setText("Cancel");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jBCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 510, 130, -1));

        JBSignUp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBSignUp.setText("Sign Up");
        JBSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(JBSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 110, 50));

        JLBBeTheFirst.setFont(new java.awt.Font("Tahoma", 2, 14));
        JLBBeTheFirst.setForeground(new java.awt.Color(204, 204, 204));
        JLBBeTheFirst.setText("Be the first of your friends to register...");
        getContentPane().add(JLBBeTheFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, -1, -1));

        JLBBurgundyRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Bigole.png"))); // NOI18N
        getContentPane().add(JLBBurgundyRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSignUpActionPerformed
        // TODO add your handling code here:
         
            RegistrationController.RegisterInSystem(this,JTFNickname.getText(), JTFName.getText(), JTFLastName.getText(), JTFSecondLastName.getText(), JTFEmail.getText(), JDCBirthDate.getDate(), JPFPassword.getText());
            
    }//GEN-LAST:event_JBSignUpActionPerformed

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        // TODO add your handling code here:
      MainWindow log = new  MainWindow ();
        log.setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_jBCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UserRegistrationWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBSignUp;
    private com.toedter.calendar.JDateChooser JDCBirthDate;
    private javax.swing.JLabel JLBBeTheFirst;
    private javax.swing.JLabel JLBBirthDate;
    private javax.swing.JLabel JLBBurgundyRegister;
    private javax.swing.JLabel JLBEmail;
    private javax.swing.JLabel JLBLastName;
    private javax.swing.JLabel JLBName;
    private javax.swing.JLabel JLBNickname;
    private javax.swing.JLabel JLBPassword;
    private javax.swing.JLabel JLBRegisterUser;
    private javax.swing.JLabel JLBSecondLastName;
    private javax.swing.JPasswordField JPFPassword;
    private javax.swing.JSeparator JSRegister1;
    private javax.swing.JSeparator JSRegister2;
    private javax.swing.JSeparator JSRegister3;
    private javax.swing.JTextField JTFEmail;
    private javax.swing.JTextField JTFLastName;
    private javax.swing.JTextField JTFName;
    private javax.swing.JTextField JTFNickname;
    private javax.swing.JTextField JTFSecondLastName;
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
private JFrame windowFather;

    public JFrame getWindowFather() {
        return windowFather;
    }

}
